export const product = {
  name: "Nowmal",
  subtitle: "Know what your inbox needs",
  principle: "Eve can read and draft. Only you can send.",
  gmailScope: "https://www.googleapis.com/auth/gmail.readonly",
  gmailSendScope: "https://www.googleapis.com/auth/gmail.send",
  gmailInitialQuery: "newer_than:30d",
  gmailInitialWindowDays: 30,
  gmailSyncDefaultMaxThreads: 100,
  gmailSyncHardMaxThreads: 500,
  workspaceAnalysisModel: "openai/gpt-5.6-terra",
  workspaceAnalysisDefaultMaxThreads: 100,
  workspaceAnalysisBatchSize: 16,
  workspaceAnalysisConcurrency: 2,
  workspaceAnalysisMessagesPerThread: 12,
  workspaceAnalysisMaxMessageChars: 3_200,
  workspaceAnalysisMinimumConfidence: 0.76,
} as const;
